#!/bin/sh

if [ -f $ZDOTDIR/neofetch.txt ];
then
	cat $ZDOTDIR/neofetch.txt
else
	dpkg -s neofetch &> /dev/null
	if [ $? -eq 0 ]; then
		neofetch --disable uptime --disable packages | tee $ZDOTDIR/neofetch.txt 
	fi
fi
